---
- name: Install Nginx and Apache on MySQL Server
  hosts: mysql
  become: yes  # Run tasks as sudo
  tasks:
    - name: Install Nginx
      ansible.builtin.package:
        name: nginx
        state: present

    - name: Write Nginx installation status to file
      ansible.builtin.lineinfile:
        path: /tmp/sw_status.txt
        line: "nginx installed successfully!!"
        create: yes

    - name: Show Nginx installation status
      ansible.builtin.debug:
        msg: "nginx installed successfully!!"

    - name: Install Apache (httpd for RHEL)
      ansible.builtin.package:
        name: httpd
        state: present

    - name: Append Apache installation status to file
      ansible.builtin.lineinfile:
        path: /tmp/sw_status.txt
        line: "apache installed successfully!!"

    - name: Show Apache installation status
      ansible.builtin.debug:
        msg: "apache installed successfully!!"

    - name: Stop Nginx to free port 80
      ansible.builtin.systemd:
        name: nginx
        state: stopped
        enabled: no

    - name: Ensure Nginx is stopped
      ansible.builtin.command: systemctl is-active nginx
      register: nginx_status
      ignore_errors: yes

    - name: Debug Nginx status
      ansible.builtin.debug:
        msg: "Nginx is {{ nginx_status.stdout }}"

    - name: Start Apache only if Nginx is stopped
      ansible.builtin.service:
        name: httpd
        state: started
      when: nginx_status.stdout == "inactive"

    - name: Append Apache start status to file
      ansible.builtin.lineinfile:
        path: /tmp/sw_status.txt
        line: "Apache started successfully!!"
      when: nginx_status.stdout == "inactive"

    - name: Show Apache start status
      ansible.builtin.debug:
        msg: "Apache started successfully!!"
      when: nginx_status.stdout == "inactive"
